// NOTE: This file is auto-generated by React Cosmos.
// It imports all fixture and decorator modules, making them available to the
// React Cosmos renderer along with the renderer config.

import type { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './src/components/atoms/Typography/__fixtures__/StyledTextDescription.fixture';
import * as fixture1 from './src/components/molecules/registerBlock/__fixture__/index';

export const rendererConfig: RendererConfig = {
  "webSocketUrl": "ws://192.168.0.106:5001",
  "rendererUrl": null
};

const fixtures = {
  'src/components/atoms/Typography/__fixtures__/StyledTextDescription.fixture.tsx': { module: fixture0 },
  'src/components/molecules/registerBlock/__fixture__/index.tsx': { module: fixture1 }
};

const decorators = {};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
